### ISSUE TITLE
Removing Member causes violation of foreign key constraint

### ISSUE THREAD

**Issue by MatthewK286** [melanger/pa165-photography-club#142]

**Comment by melanger** [comment]
I guess you cannot remove a member with equipment and/or reviews and/or tours attached? I guess the facade method could go through these linked entities and act appropriately? Do you want to look into it, @MatthewK286 ?

**Comment by MatthewK286** [comment]
I will look into it if there will be enough time :) also i noticed one issue and i dont know if its only in my machine but none of create curl command work for me not even yours(that are in cURL file) if it works for you can you try this command 
curl -i -X POST -H 'Content-Type: application/json' -d '{\"name\":\"TestMember\",\"birthDate\":\"1995-11-11\"}' 'http://localhost:8080/pa165/rest/members'
And type me back the response so I can put it in cURL file thanks

**Comment by MatthewK286** [comment]
Also this command 
curl -i -X POST -H 'Content-Type: application/json' -d '{\"tourId\":\"4\",\"authorId\":\"12\",\"comment\":\"Testing Review\"}' 'http://localhost:8080/pa165/rest/reviews'
@melanger

**Comment by melanger** [comment]
No, these don't work for me. I am using PowerShell on Windows, so I need to do
```
Remove-item alias:curl
```
and then see /equipment/ etc. in cURL.md, these work for me (quotes are escaped: `\"`).

**Comment by melanger** [comment]
When I run yours, it gives 400 Bad request (malformed).
When I run:
```
curl -i -X POST -H 'Content-Type: application/json' -d '{\"name\":\"TestMember\",\"birthDate\":\"1995-11-11\"}' 'http://localhost:8080/pa165/rest/members'
```
it gives 500 internal server error because of a NullPointerException.

**Comment by MatthewK286** [comment]
I run it on git bash and when i removed all `\` it works now :D

**Comment by MatthewK286** [comment]
Also the NullPointerException is because method createMember does not check if equipment is not null and straight away calls beanMappingService

**Comment by melanger** [comment]
I had problems when in git bash, but it works for me with only PowerShell...

**Comment by melanger** [comment]
Then please include the check and `throw EntityNotFoundException` or `PhotoEntityNotFoundException(Equipment.class)`

**Comment by melanger** [comment]
And catch it in the REST API, thanks

**Comment by MatthewK286** [comment]
well since equipment is not important to be set when creating member i have just made sure that beanMappingService is not called if equipment is null

**Comment by melanger** [comment]
Yes, that's true, it can default to empty list.

**Comment by melanger** [comment]
But please avoid storing null instead of a list.

**Comment by MatthewK286** [comment]
ok i will add empty list
