### ISSUE TITLE
Setup your git commit email adresses properly

### ISSUE THREAD

**Issue by melanger** [melanger/pa165-photography-club#87]
You are not committing with your GitHub's account email address.
Your commits appear to be authored e.g. as denis.figula@embedit.cz (@DenisFigula) or matus@147.251.201.43 (@MatthewK286). According to GitHub's help, you might be able to fix that by adding those addresses [to your account](https://github.com/settings/emails). You might also check [Setting your commit email address in Git](https://help.github.com/articles/setting-your-commit-email-address-in-git/).

**Comment by MatthewK286** [comment]
It should be set correctly now
